[package]
authors = ["Devon Govett <devongovett@gmail.com>"]
name = "parcel-hash"
version = "0.1.0"

[lib]
crate-type = ["cdylib"]

[dependencies]
napi = "2.3.3"
napi-derive = "2"
xxhash-rust = { version = "0.8.2", features = ["xxh3"] }

[build-dependencies]
napi-build = "1"
